import Foundation

/// The possible lifecycle states of a task (`lf.a2a.v1.TaskState`).
///
/// Serialized using the proto3 JSON enum mapping, e.g. `"TASK_STATE_COMPLETED"`.
public enum TaskState: String, Sendable, Codable, CaseIterable {
    case unspecified = "TASK_STATE_UNSPECIFIED"
    case submitted = "TASK_STATE_SUBMITTED"
    case working = "TASK_STATE_WORKING"
    case completed = "TASK_STATE_COMPLETED"
    case failed = "TASK_STATE_FAILED"
    case canceled = "TASK_STATE_CANCELED"
    case inputRequired = "TASK_STATE_INPUT_REQUIRED"
    case rejected = "TASK_STATE_REJECTED"
    case authRequired = "TASK_STATE_AUTH_REQUIRED"

    /// Whether the task has reached a terminal state and will not change again.
    public var isTerminal: Bool {
        switch self {
        case .completed, .failed, .canceled, .rejected:
            return true
        case .unspecified, .submitted, .working, .inputRequired, .authRequired:
            return false
        }
    }

    /// Whether the task is paused waiting on the client (input or authentication).
    public var isInterrupted: Bool {
        switch self {
        case .inputRequired, .authRequired:
            return true
        case .unspecified, .submitted, .working, .completed, .failed, .canceled, .rejected:
            return false
        }
    }
}

/// A container for the status of a task (`lf.a2a.v1.TaskStatus`).
public struct TaskStatus: Sendable, Codable, Equatable {
    /// The current state of this task.
    public var state: TaskState
    /// A message associated with the status.
    public var message: Message?
    /// ISO 8601 timestamp when the status was recorded, e.g. "2023-10-27T10:00:00Z".
    /// Kept as a string to round-trip fractional precision losslessly.
    public var timestamp: String?

    public init(state: TaskState, message: Message? = nil, timestamp: String? = nil) {
        self.state = state
        self.message = message
        self.timestamp = timestamp
    }
}

/// A task output (`lf.a2a.v1.Artifact`).
public struct Artifact: Sendable, Codable, Equatable {
    /// Unique identifier (e.g. UUID) for the artifact, unique within a task.
    public var artifactId: String
    /// A human readable name for the artifact.
    public var name: String?
    /// A human readable description of the artifact.
    public var description: String?
    /// The content of the artifact. Must contain at least one part.
    public var parts: [Part]
    /// Metadata included with the artifact.
    public var metadata: [String: JSONValue]?
    /// The URIs of extensions that are present or contributed to this artifact.
    public var extensions: [String]

    public init(
        artifactId: String,
        name: String? = nil,
        description: String? = nil,
        parts: [Part],
        metadata: [String: JSONValue]? = nil,
        extensions: [String] = []
    ) {
        self.artifactId = artifactId
        self.name = name
        self.description = description
        self.parts = parts
        self.metadata = metadata
        self.extensions = extensions
    }

    private enum CodingKeys: String, CodingKey {
        case artifactId, name, description, parts, metadata, extensions
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        artifactId = try container.decode(String.self, forKey: .artifactId)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        parts = try container.decodeIfPresent([Part].self, forKey: .parts) ?? []
        metadata = try container.decodeIfPresent([String: JSONValue].self, forKey: .metadata)
        extensions = try container.decodeIfPresent([String].self, forKey: .extensions) ?? []
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artifactId, forKey: .artifactId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(parts, forKey: .parts)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        if !extensions.isEmpty {
            try container.encode(extensions, forKey: .extensions)
        }
    }
}

/// The core unit of action for A2A (`lf.a2a.v1.Task`).
///
/// Named `A2ATask` in Swift to avoid colliding with `Swift.Task` from the
/// concurrency library. The JSON representation is unchanged.
public struct A2ATask: Sendable, Codable, Equatable {
    /// Unique identifier (e.g. UUID) for the task, generated by the server.
    public var id: String
    /// Unique identifier for the contextual collection of interactions.
    public var contextId: String?
    /// The current status of the task.
    public var status: TaskStatus
    /// A set of output artifacts for the task.
    public var artifacts: [Artifact]
    /// The history of interactions from the task.
    public var history: [Message]
    /// A key/value object to store custom metadata about the task.
    public var metadata: [String: JSONValue]?

    public init(
        id: String,
        contextId: String? = nil,
        status: TaskStatus,
        artifacts: [Artifact] = [],
        history: [Message] = [],
        metadata: [String: JSONValue]? = nil
    ) {
        self.id = id
        self.contextId = contextId
        self.status = status
        self.artifacts = artifacts
        self.history = history
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case id, contextId, status, artifacts, history, metadata
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        contextId = try container.decodeIfPresent(String.self, forKey: .contextId)
        status = try container.decode(TaskStatus.self, forKey: .status)
        artifacts = try container.decodeIfPresent([Artifact].self, forKey: .artifacts) ?? []
        history = try container.decodeIfPresent([Message].self, forKey: .history) ?? []
        metadata = try container.decodeIfPresent([String: JSONValue].self, forKey: .metadata)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(contextId, forKey: .contextId)
        try container.encode(status, forKey: .status)
        if !artifacts.isEmpty {
            try container.encode(artifacts, forKey: .artifacts)
        }
        if !history.isEmpty {
            try container.encode(history, forKey: .history)
        }
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

/// An event notifying the client of a change in task status (`lf.a2a.v1.TaskStatusUpdateEvent`).
public struct TaskStatusUpdateEvent: Sendable, Codable, Equatable {
    /// The ID of the task that has changed.
    public var taskId: String
    /// The ID of the context that the task belongs to.
    public var contextId: String
    /// The new status of the task.
    public var status: TaskStatus
    /// Metadata associated with the task update.
    public var metadata: [String: JSONValue]?

    public init(
        taskId: String,
        contextId: String,
        status: TaskStatus,
        metadata: [String: JSONValue]? = nil
    ) {
        self.taskId = taskId
        self.contextId = contextId
        self.status = status
        self.metadata = metadata
    }
}

/// A task delta where an artifact has been generated (`lf.a2a.v1.TaskArtifactUpdateEvent`).
public struct TaskArtifactUpdateEvent: Sendable, Codable, Equatable {
    /// The ID of the task for this artifact.
    public var taskId: String
    /// The ID of the context that this task belongs to.
    public var contextId: String
    /// The artifact that was generated or updated.
    public var artifact: Artifact
    /// If true, the content should be appended to a previously sent artifact with the same ID.
    public var append: Bool
    /// If true, this is the final chunk of the artifact.
    public var lastChunk: Bool
    /// Metadata associated with the artifact update.
    public var metadata: [String: JSONValue]?

    public init(
        taskId: String,
        contextId: String,
        artifact: Artifact,
        append: Bool = false,
        lastChunk: Bool = false,
        metadata: [String: JSONValue]? = nil
    ) {
        self.taskId = taskId
        self.contextId = contextId
        self.artifact = artifact
        self.append = append
        self.lastChunk = lastChunk
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case taskId, contextId, artifact, append, lastChunk, metadata
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        taskId = try container.decode(String.self, forKey: .taskId)
        contextId = try container.decode(String.self, forKey: .contextId)
        artifact = try container.decode(Artifact.self, forKey: .artifact)
        append = try container.decodeIfPresent(Bool.self, forKey: .append) ?? false
        lastChunk = try container.decodeIfPresent(Bool.self, forKey: .lastChunk) ?? false
        metadata = try container.decodeIfPresent([String: JSONValue].self, forKey: .metadata)
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(taskId, forKey: .taskId)
        try container.encode(contextId, forKey: .contextId)
        try container.encode(artifact, forKey: .artifact)
        if append {
            try container.encode(append, forKey: .append)
        }
        if lastChunk {
            try container.encode(lastChunk, forKey: .lastChunk)
        }
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}
